/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Database;
import GUI.Dialogs.DetaliiDlg;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Logic.*;

/**
 *
 * @author Remus
 */
public class UI extends javax.swing.JFrame {
    
    public String spectacoleData[][]; //matricea folosita pentru stocarea datelor despre spectacole
    public String actoriData[][];
    public double cheltuieliTotaleActori=0;
    
     public void actualizeazaSpectacolele()
    {
        //Citeste rutele din baza de date
        try
        {
            ArrayList<String[]> data = Database.ToateSpectacolele();
            spectacoleData = new String[data.size()][8];
            
            for(int row = 0; row < data.size(); row++)
            {
                spectacoleData[row][0]=data.get(row)[0];
                spectacoleData[row][1]=data.get(row)[1];
                spectacoleData[row][2]=data.get(row)[3];
                spectacoleData[row][3]=data.get(row)[4];
                spectacoleData[row][4]=data.get(row)[5];
                spectacoleData[row][5]=data.get(row)[6];
                spectacoleData[row][6]=data.get(row)[7];
                spectacoleData[row][7]=data.get(row)[8];    
          
            }
            tableSpectacole.setModel(new javax.swing.table.DefaultTableModel(
                spectacoleData, new String []
                {
                    "ID", "Titlu", "Pret balcon", "Pret loja", "Pret parter", "Data", "Ora", "Durata"
                })
            );
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex, "Eroare", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     public void ActualizeazaActorii()
    {
        //Citeste rutele din baza de date
        try
        {
            ArrayList<String[]> data = Database.TotiActorii();
            actoriData = new String[data.size()][5];
            
            for(int row = 0; row < data.size(); row++)
                for(int colum=0;colum<5; colum++)     
                    {
                        if (colum==2){
                            cheltuieliTotaleActori+=Double.parseDouble(data.get(row)[colum]);
                        }
                        actoriData[row][colum]=data.get(row)[colum]; 
                    }
            
            actoriTable.setModel(new javax.swing.table.DefaultTableModel(
                actoriData, new String []
                {
                    "ID", "Nume", "Salar brut", "Salar net", "Impozit"
                })
            );
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex, "Eroare", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        Database.Init();
        actualizeazaSpectacolele();
        ActualizeazaActorii();
        totalCheltuieliActoriTextField.setText(String.valueOf(cheltuieliTotaleActori));
        spectacolePanel.setVisible(false);
        actoriPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        menuPanel = new javax.swing.JPanel();
        plati_actoriBtn = new javax.swing.JButton();
        spectacoleBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        plati_actoriBtn1 = new javax.swing.JButton();
        spectacolePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableSpectacole = new javax.swing.JTable();
        buttonDetalii = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbAnul = new javax.swing.JComboBox();
        cmbLuna = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        actoriPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actoriTable = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalCheltuieliActoriTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(124, 125, 183));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        plati_actoriBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/clown-costume-icon.png"))); // NOI18N
        plati_actoriBtn.setText("Plati actori");
        plati_actoriBtn.setToolTipText("Detalii despre contractele actorilor ");
        plati_actoriBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plati_actoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plati_actoriBtnActionPerformed(evt);
            }
        });

        spectacoleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/trailer-icon (1).png"))); // NOI18N
        spectacoleBtn.setText("Spectacole");
        spectacoleBtn.setToolTipText("Detalii despre spectacolele ce urmeaza sa se desfasoare");
        spectacoleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spectacoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spectacoleBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Meniu");

        plati_actoriBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plati_actoriBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Log-Out-icon.png"))); // NOI18N
        plati_actoriBtn1.setText("Iesire ");
        plati_actoriBtn1.setToolTipText("Detalii despre contractele actorilor ");
        plati_actoriBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plati_actoriBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plati_actoriBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(spectacoleBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(plati_actoriBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plati_actoriBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(spectacoleBtn)
                .addGap(30, 30, 30)
                .addComponent(plati_actoriBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(plati_actoriBtn1)
                .addGap(36, 36, 36))
        );

        menuPanel.setBounds(0, 10, 161, 450);
        jLayeredPane1.add(menuPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        spectacolePanel.setBackground(new java.awt.Color(161, 161, 146));
        spectacolePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tableSpectacole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tableSpectacole);

        buttonDetalii.setFont(new java.awt.Font("Tahoma 11", 1, 12)); // NOI18N
        buttonDetalii.setText("Detalii");
        buttonDetalii.setActionCommand("detaliiButton");
        buttonDetalii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetaliiActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(215, 228, 242));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Selectare spectacole:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Anul");

        cmbAnul.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012" }));
        cmbAnul.setSelectedIndex(2);

        cmbLuna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ianuarie", "Februarie", "Martie", "Aprilie", "Mai ", "Iunie", "Iulie", "August", "Septembrie", "Octombrie", "Noiembrie", "Decembrie", "Toate" }));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Luna");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAnul, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLuna, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbAnul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbLuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Spectacole:");

        javax.swing.GroupLayout spectacolePanelLayout = new javax.swing.GroupLayout(spectacolePanel);
        spectacolePanel.setLayout(spectacolePanelLayout);
        spectacolePanelLayout.setHorizontalGroup(
            spectacolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spectacolePanelLayout.createSequentialGroup()
                .addGroup(spectacolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spectacolePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(spectacolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                            .addGroup(spectacolePanelLayout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDetalii, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(spectacolePanelLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        spectacolePanelLayout.setVerticalGroup(
            spectacolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spectacolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(spectacolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDetalii, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        spectacolePanel.setBounds(170, 10, 700, 450);
        jLayeredPane1.add(spectacolePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        actoriPanel.setBackground(new java.awt.Color(161, 161, 146));
        actoriPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Plati actori:");

        actoriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(actoriTable);

        jPanel14.setBackground(new java.awt.Color(215, 228, 242));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Total cheltuieli actori:");

        totalCheltuieliActoriTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCheltuieliActoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalCheltuieliActoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout actoriPanelLayout = new javax.swing.GroupLayout(actoriPanel);
        actoriPanel.setLayout(actoriPanelLayout);
        actoriPanelLayout.setHorizontalGroup(
            actoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actoriPanelLayout.createSequentialGroup()
                .addGroup(actoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actoriPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actoriPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actoriPanelLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel3)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        actoriPanelLayout.setVerticalGroup(
            actoriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actoriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        actoriPanel.setBounds(170, 10, 700, 450);
        jLayeredPane1.add(actoriPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDetaliiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetaliiActionPerformed
        // TODO add your handling code here:
        DetaliiBilet detBilet;
        int row=tableSpectacole.getSelectedRow(); //returneaza randul selectat (spectacolul selectat)
        double pret_balcon=0,pret_loja=0,pret_parter=0;
        
        String id = spectacoleData[row][0]; // extragem date despre spectacol 
        String titlu=spectacoleData[row][1];     
        try{
        pret_balcon=Double.parseDouble(spectacoleData[row][2]);
        pret_loja=Double.parseDouble(spectacoleData[row][3]);
        pret_parter=Double.parseDouble(spectacoleData[row][4]);
        }
        catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null, e,"Eroare",JOptionPane.ERROR_MESSAGE);
        }
        
        
        detBilet=Database.GenereazaDetaliiBilet(id,titlu,pret_balcon,pret_loja,pret_parter);
        
        DetaliiDlg dd = new DetaliiDlg(null, true);
        dd.setLocationRelativeTo(tableSpectacole);
        dd.setTxtFields(detBilet.titlu_spectacol,detBilet.incasari_spectacol, detBilet.balcon_total, detBilet.loja_total, detBilet.parter_total, detBilet.balcon_vandut, detBilet.loja_vandut, detBilet.parter_vandut);
        dd.setVisible(true);
    }//GEN-LAST:event_buttonDetaliiActionPerformed

    private void spectacoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spectacoleBtnActionPerformed
        spectacolePanel.setVisible(true);
        actoriPanel.setVisible(false);
    }//GEN-LAST:event_spectacoleBtnActionPerformed

    private void plati_actoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plati_actoriBtnActionPerformed
        spectacolePanel.setVisible(false);
         actoriPanel.setVisible(true);
    }//GEN-LAST:event_plati_actoriBtnActionPerformed

    private void plati_actoriBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plati_actoriBtn1ActionPerformed
         this.dispose();
         System.exit(0); //calling the method is a must
    }//GEN-LAST:event_plati_actoriBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actoriPanel;
    private javax.swing.JTable actoriTable;
    private javax.swing.JButton buttonDetalii;
    private javax.swing.JComboBox cmbAnul;
    private javax.swing.JComboBox cmbLuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton plati_actoriBtn;
    private javax.swing.JButton plati_actoriBtn1;
    private javax.swing.JButton spectacoleBtn;
    private javax.swing.JPanel spectacolePanel;
    private javax.swing.JTable tableSpectacole;
    private javax.swing.JTextField totalCheltuieliActoriTextField;
    // End of variables declaration//GEN-END:variables
}
